services:

    ### REPOS ###
    loopanime.anime.crawler.repo:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: ["LoopAnime\CrawlersBundle\Entity\AnimesCrawlers"]

    loopanime.parser.tvdb:
        class: LoopAnime\AppBundle\Parser\Implementation\TheTVDB
        arguments: [%tvdb_key%, %kernel.root_dir%]

    loopanime.commmand.createanime:
        class: LoopAnime\AppBundle\Command\Anime\Handler\CreateAnimeCommandHandler
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: command_handler, handles: LoopAnime\AppBundle\Command\Anime\CreateAnime }

    loopanime.commmand.editanime:
        class: LoopAnime\AppBundle\Command\Anime\Handler\EditAnimeCommandHandler
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: command_handler, handles: LoopAnime\AppBundle\Command\Anime\EditAnime }

    loopanime.commmand.createlink:
        class: LoopAnime\AppBundle\Command\Anime\Handler\CreateLinkCommandHandler
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: command_handler, handles: LoopAnime\AppBundle\Command\Anime\CreateLink }

    loopanime.sync.form.myanimelist:
        class: LoopAnime\AppBundle\Sync\Form\Type\MyAnimeListFormType
        arguments: ["@doctrine.orm.entity_manager","@security.token_storage"]
        tags:
            - { name: "form.type", alias: "loopanime_sync_form_myanimelist" }

    loopanime.sync.form.trakttv:
        class: LoopAnime\AppBundle\Sync\Form\Type\TraktTvFormType
        arguments: ["@doctrine.orm.entity_manager","@security.token_storage"]
        tags:
            - { name: "form.type", alias: "loopanime_sync_form_trakttv" }

    sync.handler.trakt:
        class: LoopAnime\AppBundle\Sync\Handler\TraktTvHandler
        arguments: ["%sync.trakt_key%", "@doctrine.orm.entity_manager"]
        tags:
            -  { name: sync.handler }

    sync.handler.mal:
        class: LoopAnime\AppBundle\Sync\Handler\MyAnimeListHandler
        arguments: ["%sync.mal_key%", "@doctrine.orm.entity_manager"]
        tags:
            -  { name: sync.handler }
    sync.service:
        class: LoopAnime\AppBundle\Sync\Services\SyncService

    ### QUEUE ###
    queue.worker.addseries:
        class: LoopAnime\AppBundle\Queue\Worker\Serie\AddSerieWorker
        tags:
            - { name: queue.worker }
    queue.worker.populate:
        class: LoopAnime\AppBundle\Queue\Worker\Serie\PopulateEpisodeWorker
        tags:
            - { name: queue.worker }
    queue.worker.syncuser:
        class: LoopAnime\AppBundle\Queue\Worker\User\SyncUserWorker
        tags:
            - { name: queue.worker }
    queue.service:
        class: LoopAnime\AppBundle\Queue\Services\QueueService
        arguments: [@doctrine.orm.entity_manager, @queue.worker.factory]

    queue.worker.factory:
        class: LoopAnime\AppBundle\Queue\Worker\WorkerFactory
        arguments: [@doctrine.orm.entity_manager, @service_container]
    queue.console.server:
        class: LoopAnime\AppBundle\Queue\ConsoleCommand\QueueConsoleCommand
        tags:
            - { name: console.command }
    queue.console.populate:
        class: LoopAnime\AppBundle\Queue\ConsoleCommand\Creators\PopulateTodaysEpisodesConsoleCommand
        tags:
            - { name: console.command }
    queue.console.sync:
        class: LoopAnime\AppBundle\Queue\ConsoleCommand\Creators\SyncEpisodesConsoleCommand
        tags:
            - { name: console.command }

    ## CRAWLER ##
    crawler.service:
        class: LoopAnime\AppBundle\Crawler\Service\CrawlerService
        arguments: [@doctrine.orm.entity_manager]

    crawler.strategy.serie:
        class: LoopAnime\AppBundle\Crawler\Strategy\SerieSearchStrategy
        arguments: [@loopanime.anime.crawler.repo, @cache]

    crawler.strategy.episode:
        class: LoopAnime\AppBundle\Crawler\Strategy\EpisodeSearchStrategy
        arguments: [@loopanime.anime.crawler.repo, @cache]

    crawler.hoster.anitube:
        class: LoopAnime\AppBundle\Crawler\Hoster\AnitubeHoster

    crawler.hoster.anime44:
        class: LoopAnime\AppBundle\Crawler\Hoster\Anime44Hoster