loopanime_comments_listEpisodesComments:
    pattern:  /episodes/listComments.{_format}?{idEpisode}
    requirements: {"_format": "html|json"}
    defaults: {_controller: LoopAnimeCommentsBundle:Comments:listEpisodesComments, _format: "html"}