loopanime_shows_listEpisodesComments:
    pattern:  /list-comments.{_format}?{idEpisode}
    requirements: {"_format": "html|json"}
    defaults: {_controller: LoopAnimeCommentsBundle:Comments:listEpisodesComments, _format: "html"}
loopanime_comments_createComment:
    pattern: /create-comment/{episode}/
    requirements: {"_format": "html|json"}
    defaults: {_controller: LoopAnimeCommentsBundle:Comments:commentEpisode, _format: "html" }