parameters:
#    loop_anime_comments.example.class: LoopAnime\CommentsBundle\Example

services:
#    loop_anime_comments.example:
#        class: %loop_anime_comments.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
