parameters:
#    loop_anime_comments.example.class: LoopAnime\CommentsBundle\Example

services:
    comment.service:
        class: LoopAnime\CommentsBundle\Services\CommentsService
        arguments: ["@doctrine.orm.entity_manager"]
