fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /users_cp

loopanime_user_setPreferences:
    pattern: /users/set-preferences
    defaults: {_controller: LoopAnimeUsersBundle:UserActions:setPreferences}
loopanime_users_listUsers:
    pattern: /users/list-users.{_format}
    requirements: {_format: "html|json"}
    defaults: {_controller: LoopAnimeUsersBundle:UserActions:listUsers, _format: "html"}
loopanime_users_user:
    pattern: /users/{idUser}.{_format}
    requirements: {_format: "html|json"}
    defaults: {_controller: LoopAnimeUsersBundle:UserActions:getUser, _format: "html"}
loopanime_usercp_listFavAnimes:
    pattern: /users_cp/listFavAnimes.{_format}
    requirements: {_format: "html|json"}
    defaults: {_controller: LoopAnimeUsersBundle:UserCP:listFavAnimes, _format: "html"}
loopanime_usercp_listTrackAnimes:
    pattern: /users_cp/listTrackAnimes.{_format}
    requirements: {_format: "html|json"}
    defaults: {_controller: LoopAnimeUsersBundle:UserCP:listTrackedAnimes, _format: "html"}
loopanime_usercp:
    pattern: /users_cp
    requirements: {_format: "html"}
    defaults: {_controller: LoopAnimeUsersBundle:UserCP:index, _format: "html"}