parameters:
    my_user_provider.class: LoopAnime\UsersBundle\Security\Core\User\FOSUBUserProvider

services:
    loopanime.registration.form.type:
        class: LoopAnime\UsersBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%, "@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: loopanime_user_registration }
    loopanime.invitation.form.type:
        class: LoopAnime\UsersBundle\Form\Type\InvitationFormType
        arguments: [@loopanime.invitation.form.data_transformer]
        tags: [{ name: "form.type", alias: "loopanime_invitation_type" }]
    loopanime.invitation.form.data_transformer:
        class: LoopAnime\UsersBundle\Form\DataTransformer\InvitationToCodeTransformer
        arguments: [@doctrine.orm.entity_manager]
    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id}]
    loopanime.users.listener.user_listener:
        class: LoopAnime\UsersBundle\EventListener\UserListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: user.create, method: onUserCreate }