parameters:
#    loop_anime_general.example.class: LoopAnime\GeneralBundle\Example

services:
#    loop_anime_general.example:
#        class: %loop_anime_general.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
