parameters:
#    loop_anime_shows.example.class: LoopAnime\Bundle\ShowsBundle\Example

services:
#    loop_anime_shows.example:
#        class: %loop_anime_shows.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
