loopanime_search_form:
    pattern: /form
    defaults: { _controller: LoopAnimeSearchBundle:Search:searchForm }
loopanime_search_search:
    pattern: /{term}
    defaults: { _controller: LoopAnimeSearchBundle:Search:search, term: null }