parameters:
#    loop_anime_crawlers.example.class: LoopAnime\CrawlersBundle\Example

services:
#    loop_anime_crawlers.example:
#        class: %loop_anime_crawlers.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
