parameters:
    sync.trakt_key: dd60c58d4da36923babae412527fe818
    sync.mal_key: api-indiv-4AE2A5690C1650AA1177A8C7FED8BB5B

services:
    loopanime.showapi.tvdb:
        class: LoopAnime\ShowsAPIBundle\Services\Apis\TheTVBD
        arguments: ["@doctrine.orm.entity_manager",%kernel.root_dir%]
    sync.trakt:
        class: LoopAnime\ShowsAPIBundle\Services\SyncAPI\TraktTV
        arguments: ["%sync.trakt_key%", "@security.context", "@doctrine.orm.entity_manager"]
    sync.mal:
        class: LoopAnime\ShowsAPIBundle\Services\SyncAPI\MAL
        arguments: ["%sync.mal_key%", "@security.context", "@doctrine.orm.entity_manager"]